[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# --- Solusi EIP-170 ---
optimizer = true
optimizer_runs = 300 # Nilai rendah untuk kontrak Factory
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
